#!/usr/bin/env python3
from pymongo import MongoClient


def use_or_create_database():
    client = MongoClient('mongodb://127.0.0.1:27017')
    db = client.my_db


if __name__ == "__main__":
    use_or_create_database()
